### ISSUE TITLE
Incompatible with Anki 2.1.28

### ISSUE THREAD

**Issue by jsands214** [lovac42/HoochieMama#22]
this is one of my absolute favorite add-ons, thank you for making it!!! This is the error that I got when starting Anki after updating to 2.1.28:

When loading '⁨HoochieMama Randomize Rev Queue⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 211, in loadAddons
  File "C:\Users\jenna\AppData\Roaming\Anki2\addons21\1460733408\__init__.py", line 10, in <module>
    from . import hoochieMama
  File "C:\Users\jenna\AppData\Roaming\Anki2\addons21\1460733408\hoochieMama.py", line 206, in <module>
    anki.sched.Scheduler._resetRevCount, resetRevCount, 'around'
AttributeError: type object 'Scheduler' has no attribute '_resetRevCount'

**Comment by VincentOostelbos** [comment]
Can confirm, I get the same error message for 2.1.29. I believe it occurred in any version from 2.1.25 onward, if that helps. The addon does seem to stay active in the addon list, regardless of the error message.

**Comment by Willz7** [comment]
The addon does not support anything after 2.1.23 (    Anki Version: 2.1.22 (Windows and Linux), 2.1.23 (macOS) 
https://ankiweb.net/shared/info/1460733408

**Comment by landonepps** [comment]
`_resetRevCount` was removed by this commit
https://github.com/ankitects/anki/commit/8b57a61746f0f20f6ee3b8c6a2da2436d2d39fbb

It seems to have been replaced with a `_reset_counts` function. I wonder if this can be used instead...
